# this action message is for the general use of swarm robot trajectory interpolation action
# variable-length array means multiple robots

# goal definition
float64[] x  # x coordinate of robots in the world
float64[] y  # y coordinate of robots in the world
float64 time_cost  # time need for this action
---
# result definition
int32[] err_code
string[] err_msg
---
# feedback
int32[] fdbk

